### ISSUE TITLE
Multi byte character copy/paste issue

### ISSUE THREAD

**Issue by KazukiOhno** [ultravnc/UltraVNC#72]
Thank you for very nice program with open source. I use UltraVNC on Windows11 and connect to Raspberry Pi.
But I have a trouble when I select Japanese character, I can't find '?' instead of Japanese character. On the other hand, current program is no problem when I copy/paste 1 byte character like ASCII.

I'm looking for how to fix multi byte character copy from Raspberry Pi to Windows.
I suppose ReadServerCutText in ClientConnection.cpp can handle only 1 byte character. Perhaps ReadString() function in this ReadServerCutText was made based on 1 byte charater text case only.

However I could not know how to get text from clipboard on this program. In UltraVNC, I can copy/paste including Japanese character correctly. So, if I could have multi byte character or Unicode in this program, I would translate shift JIS (Japanese standard character code on WIndows).
Because when I put shift JIS code into m_netbuf in the function of ReadServerCutText(), I could paste test with Japanese character onto Windows. Thank you for your help or advise.

**Comment by RudiDeVos** [comment]
The Japanaese keyboard is working.
You need to select it on the viewer.
![image](https://user-images.githubusercontent.com/71467484/220180615-bfe41775-1623-48e0-943d-926316c4b431.png)
But that wil not help with a non vnc viewer.
Try server settings
![image](https://user-images.githubusercontent.com/71467484/220180802-63f29912-f34f-43c1-a902-3096c429af40.png)

**Comment by KazukiOhno** [comment]
Thank you for your advice, but my point is different.

![cap1](https://user-images.githubusercontent.com/45531499/220335794-cb8bd102-ddd2-4b15-b7b1-9644f83eea51.png)
I'd like to ask  as this picture.
日本 is Japan in chinese charcter on Raspberry Pi. And I select them and copy. Then go to Windows Memo pad and paste to it. Then I only get have ?? instead of 日本.
When I try to fix this, I found UltraVNC handles multi byte character as byte.
On Windows, Japanese character code is shift JIS=SJIS. 日本 case, 0x93FA, 0x967B.

On the other hand, I copy same word 日本 on Windows and paste to RPi on VNC. I could find below picture.
![cap2](https://user-images.githubusercontent.com/45531499/220338184-6b7e3a77-e17c-4e54-af33-e1692514267e.png)
On RPi, it uses UNICODE, I understand SJIS code just appears on the screen. Then I can see like 0x93 u (umlaut) and 0x96 {  insted of 日本 word.
If I can translate SJIS to Unicode, I might get correct Japanese.

If this explanation helps you to understand, I'm happy.

**Comment by RudiDeVos** [comment]
Clipboard format is CF_UNICODETEXT
see Clipboard.cpp line 192

But this is the extendedClipboard, both viewer and server need to understand extendedClipboard protocol.

rfbproto.h
..
```
typedef struct {
    CARD8 type;			/* always rfbServerCutText */
    CARD8 pad1;
    CARD16 pad2;
    CARD32 length; // will be negative to notify viewer that it accepts extended clipboard data.
	// adzm - 2010-07 - Extended clipboard support
	/*
	rfbEncodingExtendedClipboard provides extended clipboard functionality.
	If extended clipboard data is being used, the length will be negative.
	The message follows with unsigned char[abs(length)] data. The first sz_rfbExtendedClipboardData is the rfbExtendedClipboardData struct.
	The server notifies the viewer that it accepts the rfbEncodingExtendedClipboard extension to the protocol
	by immediately sending an rfbServerCutTextMsg with the clipCaps flags set in rfbExtendedClipboardData,
	which determines current version and also size limits of the main clipboard formats.

	if using classic clipboard, followed by char text[length]
    */
} rfbServerCutTextMsg;
```

**Comment by KazukiOhno** [comment]
Thank you, RudiDeVos,
I already checked rfbServerCutTextMsg structure but I didn't know Clipboard.cpp has UNICODE. 
Then I think this issue comes from Server side VNC. On my RaspberryPi uses RealVNC. This might not have a capability extended Clipboard or Multi Byte Char code.
Much appreciate you to teach me kindly how to manage UNICODE on UltraVNC.
I should close this topic.

**Comment by KazukiOhno** [comment]
I asked RealVNC, then I could find a solution. That is using RealVNC viewer on Windows. Now I have RealVNC on RaspberryPi with RealVNC server and RealVNC viewer on Windows, then my problem was resolved. There is no issue on copy/paste Japanese text (multi byte code) each other.

**Comment by Neustradamus** [comment]
@KazukiOhno: With UltraVNC Viewer, it does not work?
Have you tested the 1.4.2.2-dev?
- https://forum.uvnc.com/viewtopic.php?t=37794

If it does not work, there is a problem to fix...

**Comment by KazukiOhno** [comment]
Thank you for informing me this version update.

I installed this version and checked whether previous matter is 
improved. Unfortunately, no change from previous version.

When I copy the text on UltraVNC including Japanese Kanji character and 
paste on Windows11 memopad, multi byte character replaces by '?'. This 
is same phenomena as previous version.

I just report to you. I appreciate you to continue to provide UltraVNC 
to all.


Thanks,

Kazuki Ohno

**Comment by Neustradamus** [comment]
@KazukiOhno: Thanks for your comment, can you reopen your ticket?

**Comment by Neustradamus** [comment]
@KazukiOhno: It is same with 1.4.3.1? If yes, can you reopen your ticket?
Please look screenshots: https://github.com/ultravnc/UltraVNC/issues/72#issuecomment-1437425475

**Comment by KazukiOhno** [comment]
Thank you for asking. I installed new version 1.4.3.17 and tried to copy Japanese (multi byte character) and paste on Windows. Unfortunately, it does not work well as previous version. I don't want to reopen this topic. Because I could find RealVNC works well and move to RealVNC. I hope UltraVNC also could work multi byte character handling. I like UltaraVNC. Thank you!

**Comment by Neustradamus** [comment]
@KazukiOhno: You must to reopen, UltraVNC is not another VNC client ;)

@RudiDeVos: It is always here :/

**Comment by RudiDeVos** [comment]
unicode is handled in an extension in UltraVNC, this is only available for clients using this extension.
When i alot of time i need to check if the default can be changed without breaking any backward compatibility with UltraVNC.

**Comment by Neustradamus** [comment]
@KazukiOhno: Can you try 1.5.0.3-dev? It is same?
- https://forum.uvnc.com/viewtopic.php?t=37976

**Comment by Neustradamus** [comment]
Character problem is linked to tickets:
- https://github.com/ultravnc/UltraVNC/issues/332
- https://github.com/ultravnc/UltraVNC/issues/323
- https://github.com/ultravnc/UltraVNC/issues/253
- https://github.com/ultravnc/UltraVNC/issues/240
- https://github.com/ultravnc/UltraVNC/issues/214
- https://github.com/ultravnc/UltraVNC/issues/211
- https://github.com/ultravnc/UltraVNC/issues/124
- https://github.com/ultravnc/UltraVNC/issues/72
- https://github.com/ultravnc/UltraVNC/issues/64
- https://github.com/ultravnc/UltraVNC/issues/7#issuecomment-1003742782

For me it is linked to keymap.

**Comment by Neustradamus** [comment]
@KazukiOhno: Can you try the 1.7.1.2-dev release build?
- https://uvnc.eu/download/1710/UltraVNC_1712_x86_Setup.exe
- https://uvnc.eu/download/1710/UltraVNC_1712_x64_Setup.exe

It has been solved?

**Comment by RudiDeVos** [comment]
solved

**Comment by Neustradamus** [comment]
@KazukiOhno: At this time, can you try the 1.7.1.5-dev release build?
- https://uvnc.eu/download/1710/UltraVNC_1715-dev.zip
- https://uvnc.eu/download/1710/UltraVNC_1715_x64_Setup.exe
- https://uvnc.eu/download/1710/UltraVNC_1715_x86_Setup.exe

An answer is very important...

**Comment by KazukiOhno** [comment]
Thank you for following up this.

And sorry for my slow response. I checked latest version of UltraVNC 
1.7.1.5.

Unfortunately, situation looks same as before. I couldn't paste multi 
byte character from Windows to UltraVNC. I used emacs 27.1 and Windows11 
Pro 25H2.

As I mentioned RealVNC works fine.

Thank you for supporting this issue.

Kazuki Ohno

**Comment by KazukiOhno** [comment]
Hi, Neustradamus,

I tried to use latest version of UltraVNC Viewer 1.7.1.8.

Unfortunately looks not fixed yet.

Below is a capture information when I pasted Japanese (multi byte 
characters from Windows PC).

Thanks,
Kazuki

**Comment by KazukiOhno** [comment]
Hi, Neustradamus,

Thank you for following up.

I checked 1.7.1.9 on my Japanese mode Windows 11 PC.

Unfortunately, nothing changed.

However, I found one thing might be a hint for this issue.

When I copy text including multi byte characters on Windows and paste it 
to emacs on UltraVNC environment, then text looks wrong coding.

On the RealVNC, it worked well without any coding error.

I checked several times this, copy text, paste text on RealVNC and paste 
text on UltraVNC. It always worked well.

This is a new point, after pasting on Real VNC, I tried to paste again 
on UltraVNC, then It also works fine. I don't know the reason but 
something happen after pasting on Real VNC.

I hope you could find a way to resolve this issue.


Thanks,

Kazuki Ohno

**Comment by KazukiOhno** [comment]
Hi,

I tried to use this new version. Unfortunately, it looks no change from 
user view point. I don't know the reason of this situation, but I would 
like to say to thank you for your update.


Thanks,

Kazuki Ohno

**Comment by Neustradamus** [comment]
@KazukiOhno: Can you specified all details for this new test with 1.8.0.5 version?
What do you use in two sides (server and viewer)...
What OS versions...

It is very important for @RudiDeVos who has done a lot of improvements recently...

**Comment by KazukiOhno** [comment]
Hello, Neustradamus,

Thank you for following me.

I tried to verify UltraVNC 1.8.0.5 of x64 version. My PC is Windows 11 
Pro 25H2.

After installing it, open UltraVNCViewer on the desktop of Windows PC. 
And connected Raspberry Pi 4 Model B.

Hardware    : BCM2835
Revision    : c03114
Serial        : XXXXXXXXXXXXXXXXXXX
Model        : Raspberry Pi 4 Model B Rev 1.4

Then I copied some word in Japanese on Windows (ex. Note, One Noe, 
Chrome) and paste on Emacs, Terminal on RPi 4.

On the Window, I tried 2 cases. One is Old type SJIS code and the other 
is UTF-8 code.

Both cases happens same result as not good.

For example, ABCあいう on One note.

When pasted to emacs on UltraVNC Viewer as below.

Thanks for your big efforts,

Kazuki

**Comment by Neustradamus** [comment]
@KazukiOhno: At this time, can you try the 1.8.0.7 release build?
- https://uvnc.eu/download/1800/UltraVNC_1807_x64_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1807_x86_Setup.exe
- https://uvnc.eu/download/1800/UltraVNC_1807.zip

This version has solved some character problems, can you confirm, if it solves your case?

**Comment by KazukiOhno** [comment]
Hello, Neustradamus,

Thank you for your hard work.

I checked latest version of 1.8.0.7. Unfortunately, result is not good. 
Looks same result as before.


Thanks,

Kazuki Ohno

**Comment by Neustradamus** [comment]
@KazukiOhno: At this time, can you try the latest release build?
- https://forum.uvnc.com/viewtopic.php?t=38158

**Comment by Neustradamus** [comment]
@KazukiOhno: At this time, can you try the latest release build?
- https://forum.uvnc.com/viewtopic.php?t=38158

**Comment by KazukiOhno** [comment]
Hello, all,

Thank you for updating UltraVNC 1.8.3.0.

I checked it by same way as before. Unfortunately, it looks like same 
status as before.

When I copied Japanese text on Windows 11 and paste Emacs editor on 
UltraVNC. All character changed to the character code. On the other 
hand, RealVNC looks OK to paste Japanese text.

Thanks,

Kazuki Ohno
